USE [master]
GO

/****** Object:  Database [BHP1-RO]    Script Date: 4/23/2020 5:36:48 PM ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'BHP1-RO')
DROP DATABASE [BHP1-RO]
GO

/****** Object:  Database [BHP1-RO]    Script Date: 4/23/2020 5:36:48 PM ******/
CREATE DATABASE [BHP1-RO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BHP1-RO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MYDEV\MSSQL\DATA\BHP1-RO.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BHP1-RO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MYDEV\MSSQL\DATA\BHP1-RO_log.ldf' , SIZE = 1088KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

--ALTER DATABASE [BHP1-RO] SET COMPATIBILITY_LEVEL = 120
--GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BHP1-RO].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

--ALTER DATABASE [BHP1-RO] SET ANSI_NULL_DEFAULT OFF 
--GO

--ALTER DATABASE [BHP1-RO] SET ANSI_NULLS OFF 
--GO

--ALTER DATABASE [BHP1-RO] SET ANSI_PADDING OFF 
--GO

--ALTER DATABASE [BHP1-RO] SET ANSI_WARNINGS OFF 
--GO

--ALTER DATABASE [BHP1-RO] SET ARITHABORT OFF 
--GO

ALTER DATABASE [BHP1-RO] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BHP1-RO] SET AUTO_SHRINK ON 
GO

--ALTER DATABASE [BHP1-RO] SET AUTO_UPDATE_STATISTICS ON 
--GO

--ALTER DATABASE [BHP1-RO] SET CURSOR_CLOSE_ON_COMMIT OFF 
--GO

--ALTER DATABASE [BHP1-RO] SET CURSOR_DEFAULT  GLOBAL 
--GO

--ALTER DATABASE [BHP1-RO] SET CONCAT_NULL_YIELDS_NULL OFF 
--GO

--ALTER DATABASE [BHP1-RO] SET NUMERIC_ROUNDABORT OFF 
--GO

--ALTER DATABASE [BHP1-RO] SET QUOTED_IDENTIFIER OFF 
--GO

--ALTER DATABASE [BHP1-RO] SET RECURSIVE_TRIGGERS OFF 
--GO

--ALTER DATABASE [BHP1-RO] SET  ENABLE_BROKER 
GO

ALTER DATABASE [BHP1-RO] SET AUTO_UPDATE_STATISTICS_ASYNC ON 
GO

ALTER DATABASE [BHP1-RO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

--ALTER DATABASE [BHP1-RO] SET TRUSTWORTHY OFF 
--GO

--ALTER DATABASE [BHP1-RO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
--GO

--ALTER DATABASE [BHP1-RO] SET PARAMETERIZATION SIMPLE 
--GO

--ALTER DATABASE [BHP1-RO] SET READ_COMMITTED_SNAPSHOT OFF 
--GO

--ALTER DATABASE [BHP1-RO] SET HONOR_BROKER_PRIORITY OFF 
--GO

ALTER DATABASE [BHP1-RO] SET RECOVERY SIMPLE 
GO

--ALTER DATABASE [BHP1-RO] SET  MULTI_USER 
--GO

--ALTER DATABASE [BHP1-RO] SET PAGE_VERIFY CHECKSUM  
--GO

--ALTER DATABASE [BHP1-RO] SET DB_CHAINING OFF 
--GO

--ALTER DATABASE [BHP1-RO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
--GO

--ALTER DATABASE [BHP1-RO] SET TARGET_RECOVERY_TIME = 0 SECONDS 
--GO

--ALTER DATABASE [BHP1-RO] SET DELAYED_DURABILITY = DISABLED 
--GO

--ALTER DATABASE [BHP1-RO] SET  READ_WRITE 
--GO


